Go Raft GenerateSnapshotID Build Error
Promot:
Running `go build -v ./...` is failing with following error
```
Error: ./fsm.go:109:125: undefined: raft.GenerateSnapshotID
Error: Process completed with exit code 1.
```

I'll provide a modified version of `vibecoding/kvreplicator/fsm.go` that addresses both points:
*   It introduces a local helper function `generateLocalSnapshotID()` that replicates the logic of `raft.GenerateSnapshotID()`. This should resolve the `undefined` error by providing the function directly.
*   It corrects the `fmt.Sprintf` call to use `%s` for the snapshot ID.
*   This change will require adding `time` and `github.com/hashicorp/go-uuid` to the imports in `fsm.go`. The `github.com/hashicorp/go-uuid` package is already listed as an indirect dependency in your `go.sum`, so Go should be able to find it.