Go build error missing go sum entries
Prompt:

Running `go build -v ./...` is failing with following error
```
Error: /home/runner/go/pkg/mod/github.com/fatih/color@v1.13.0/color.go:11:2: missing go.sum entry for module providing package github.com/mattn/go-colorable (imported by github.com/fatih/color); to add:
	go get github.com/fatih/color@v1.13.0
Error: /home/runner/go/pkg/mod/github.com/fatih/color@v1.13.0/color.go:12:2: missing go.sum entry for module providing package github.com/mattn/go-isatty (imported by github.com/hashicorp/go-hclog); to add:
	go get github.com/hashicorp/go-hclog@v1.6.2
Error: Process completed with exit code 1.
```

It looks like your Go build is failing because of missing entries in your `go.sum` file. This file keeps track of the expected cryptographic checksums of the direct and indirect dependencies used in your project.

The error messages suggest running the following commands to add the missing entries:

1.  `go get github.com/fatih/color@v1.13.0`
2.  `go get github.com/hashicorp/go-hclog@v1.6.2